- name: loops
  hosts: local
  become: yes
  tasks:
  - name: print names
    ansible.builtin.package:
      name: "{{item.name}}"  #item is default keyword for ansible loops
      state: "{{item.state}}"
    loop:
    - { name: 'git' , state: 'present' }
    - { name: 'mysql' , state: 'absent' }
    - { name: 'postfix' , state: 'absent' }